export enum ProductIds {
  XBTUSD = 'PI_XBTUSD',
  ETHUSD = 'PI_ETHUSD',
}

export enum ActionType {
  OPEN_SOCKET = 'OPEN_SOCKET',
  CLOSE_SOCKET = 'CLOSE_SOCKET',
  OPEN_SOCKET_SUCCESS = 'OPEN_SOCKET_SUCCESS',
  SOCKET_SUBSCRIBE = 'SOCKET_SUBSCRIBE',
  SOCKET_UNSUBSCRIBE = 'SOCKET_UNSUBSCRIBE',
  UPDATE_ORDERBOOK = 'UPDATE_ORDERBOOK',
}
